cities:
  - Cairo
  - Paris
  - Tokyo
  - London
  - New York City
  - Istanbul
  - Buenos Aires
  - Lagos
  - Mumbai
  - Beijing
  - Mexico City
  - São Paulo
  - Berlin
  - Sydney
  - Dubai
  - Rome
  - Bangkok
  - Toronto
  - Nairobi
  - Jakarta
  - Munich

paths:
  raw_data: data/raw
  processed_data: data/processed
  indexes: data/indexes
  gold_qa: data/gold_qa

scraper:
  source: wikipedia
  auto_suggest: false